/*
 * AI_CONTEXT — Shopping Center Inventory (v1.1, re-vetted 2026-06-05)
 * This file IS the catalog. The website (index.html) builds itself from it.
 * To add/remove a tool: edit the `items` array, commit, push.
 * Fields: tier (Core|Recommended|Situational|Shortlist|Showroom), cost (Free|Free tier|Paid),
 *   pop (verified adoption blurb), popRank (1-5 for sorting), plus what/why/install/url/risk/verdict.
 * 'How it connects to Claude' is derived from `type` in app.js (MCP/Connector/Skill/CLI/Standalone).
 */
window.CATALOG = {
  "meta": {
    "title": "AI_CONTEXT",
    "tagline": "Your curated shopping center for hooking real tools into Claude.",
    "updated": "2026-06-05",
    "version": "1.1",
    "note": "Re-vetted June 2026: adoption (stars/downloads/sentiment) verified per item; 3 items removed after failing re-vetting (see docs/MAINTENANCE.md)."
  },
  "aisles": [
    {
      "id": "foundations",
      "name": "Foundations",
      "icon": "🧱",
      "blurb": "The core wiring — connect Claude to your files, repos, browser, docs and memory."
    },
    {
      "id": "orchestration",
      "name": "Orchestration",
      "icon": "🪃",
      "blurb": "Make Claude plan, delegate to subagents, and run multi-step work well."
    },
    {
      "id": "verification",
      "name": "Verification",
      "icon": "✅",
      "blurb": "Prove the code actually works."
    },
    {
      "id": "security",
      "name": "Security",
      "icon": "🔒",
      "blurb": "Secrets, vulnerabilities, and code safety."
    },
    {
      "id": "optimization",
      "name": "Optimization",
      "icon": "⚡",
      "blurb": "Speed, size, complexity, cleanliness."
    },
    {
      "id": "uiux",
      "name": "UI / UX",
      "icon": "🎨",
      "blurb": "Better front-end, components, and accessibility."
    },
    {
      "id": "visuals",
      "name": "Visuals",
      "icon": "📊",
      "blurb": "Diagrams, flowcharts, and architecture pictures."
    },
    {
      "id": "creative",
      "name": "Creative / Marketing",
      "icon": "📣",
      "blurb": "Posters, copy, brand, social, and free image generation."
    },
    {
      "id": "docs",
      "name": "Documentation",
      "icon": "📚",
      "blurb": "Docs systems, READMEs, and shared context across AI tools."
    },
    {
      "id": "data",
      "name": "Data / Documents",
      "icon": "🗃️",
      "blurb": "Databases, files, PDFs/Office, and your Obsidian vault."
    },
    {
      "id": "planning",
      "name": "Planning / Workflow",
      "icon": "🧭",
      "blurb": "Idea → demo → prototype → MVP → production."
    },
    {
      "id": "pm",
      "name": "Project Mgmt",
      "icon": "📌",
      "blurb": "Status tracking, issues, and kanban."
    },
    {
      "id": "prompting",
      "name": "Prompting",
      "icon": "✍️",
      "blurb": "Generate and enhance prompts to delegate tasks to people or AIs."
    },
    {
      "id": "compliance",
      "name": "Compliance",
      "icon": "📜",
      "blurb": "SOC 2 / ISO 27001 readiness helpers (the free technical half)."
    }
  ],
  "items": [
    {
      "id": "claude-md",
      "name": "CLAUDE.md / Memory",
      "aisle": "foundations",
      "also": [
        "docs"
      ],
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "A plain markdown file Claude Code auto-loads every session as the project's permanent rulebook (stack, conventions, commands, do-nots).",
      "why": "Highest-leverage, zero-install thing you can do. On a 50k-line project it stops you re-explaining context every time.",
      "maturity": "Official Anthropic, built into Claude Code.",
      "install": "Create CLAUDE.md in the project root. Add ~/.claude/CLAUDE.md for rules that apply to every project. Run /init to generate one.",
      "url": "https://code.claude.com/docs/en/memory",
      "risk": "Low.",
      "verdict": "Start here before installing anything.",
      "pop": "Built-in · ubiquitous · loved",
      "popRank": 5
    },
    {
      "id": "agents-md",
      "name": "AGENTS.md (cross-tool context)",
      "aisle": "foundations",
      "also": [
        "docs"
      ],
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "An open, cross-tool instruction file many agents read natively (Claude Code, Copilot, Codex, Cursor, Gemini CLI, Aider). One source of truth for all your AIs.",
      "why": "You already juggle multiple AI systems on a shared .md context — this is the standardized version. Symlink CLAUDE.md -> AGENTS.md and maintain one file.",
      "maturity": "Widely adopted open convention; plain markdown, nothing to break.",
      "install": "Create AGENTS.md at the repo root. Optionally point CLAUDE.md at it (Windows: copy the content, or use a junction).",
      "url": "https://agents.md/",
      "risk": "Low — worst case an agent ignores it gracefully.",
      "verdict": "The fix for your multi-AI shared-context system.",
      "pop": "⭐22k · cross-tool standard (Copilot/Cursor/Codex)",
      "popRank": 4
    },
    {
      "id": "mcp-filesystem",
      "name": "Filesystem MCP (official)",
      "aisle": "foundations",
      "type": "MCP server",
      "tier": "Core",
      "cost": "Free",
      "what": "Sandboxed read/write access to directories you explicitly allow.",
      "why": "Lets Claude navigate and edit your codebase safely, scoped to folders you name. Foundational for any project.",
      "maturity": "Official MCP reference server (modelcontextprotocol/servers), actively maintained, MIT.",
      "install": "claude mcp add filesystem -- npx -y @modelcontextprotocol/server-filesystem C:/Users/you/projects",
      "url": "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
      "risk": "Low — access is limited to the paths you pass in.",
      "verdict": "Non-negotiable foundation.",
      "pop": "⭐87k (MCP servers monorepo) · most-installed reference server · loved",
      "popRank": 5
    },
    {
      "id": "mcp-git",
      "name": "Git MCP (official)",
      "aisle": "foundations",
      "type": "MCP server",
      "tier": "Core",
      "cost": "Free",
      "what": "Read, search, log, diff and stage changes in local Git repos.",
      "why": "Gives Claude history/diff awareness without needing a GitHub token. Purely local.",
      "maturity": "Official MCP reference server, MIT, actively maintained.",
      "install": "claude mcp add git -- uvx mcp-server-git --repository C:/Users/you/projects/myrepo",
      "url": "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
      "risk": "Low — you set the repo path.",
      "verdict": "Essential for code-aware git work.",
      "pop": "⭐87k (MCP monorepo) · ubiquitous · loved",
      "popRank": 5
    },
    {
      "id": "github-mcp",
      "name": "GitHub MCP (official, by GitHub)",
      "aisle": "foundations",
      "also": [
        "pm"
      ],
      "type": "MCP server",
      "tier": "Core",
      "cost": "Free",
      "costNote": "needs a GitHub token",
      "what": "Full GitHub over MCP — repos, issues, PRs, code search, Actions.",
      "why": "You live on GitHub. This is GitHub's own supported server, replacing the now-archived reference one.",
      "maturity": "Official by GitHub Inc., very widely used, MIT, active.",
      "install": "Use the hosted remote server or local Docker — see the repo. Needs a GitHub PAT (start read-only).",
      "url": "https://github.com/github/github-mcp-server",
      "risk": "Low–medium — don't grant write scopes you don't need.",
      "verdict": "Replaces the archived reference GitHub server.",
      "pop": "⭐31k · GitHub-official · ships in major IDEs · loved",
      "popRank": 5
    },
    {
      "id": "context7",
      "name": "Context7 MCP (Upstash)",
      "aisle": "foundations",
      "also": [
        "docs"
      ],
      "type": "MCP server",
      "tier": "Core",
      "cost": "Free",
      "what": "Injects up-to-date, version-specific library docs into Claude's context at call time — kills hallucinated APIs.",
      "why": "A big project pulls in many libraries; Claude's training is always a bit stale. This fixes it live. One of the highest-ROI MCPs.",
      "maturity": "Upstash, ~50k★, one of the most-used MCP servers, MIT.",
      "install": "claude mcp add --transport http context7 https://mcp.context7.com/mcp",
      "url": "https://github.com/upstash/context7",
      "risk": "Low — read-only; sends library-name queries to Upstash's hosted service. Don't feed it proprietary code.",
      "verdict": "Install this first among the MCPs.",
      "pop": "⭐57k · fastest-growing MCP · ~890k npm dl/wk · loved",
      "popRank": 5
    },
    {
      "id": "playwright-mcp",
      "name": "Playwright MCP (Microsoft)",
      "aisle": "foundations",
      "also": [
        "verification",
        "uiux"
      ],
      "type": "MCP server",
      "tier": "Core",
      "cost": "Free",
      "what": "Full browser control — navigate, click, fill, screenshot, assert — via the accessibility tree (no vision model needed).",
      "why": "Lets Claude actually verify your HTML/PWA renders and works, not just that tests pass. Indispensable for solo QA.",
      "maturity": "Microsoft official, ~30k★+, Apache-2.0, extremely active.",
      "install": "claude mcp add playwright -- npx @playwright/mcp@latest",
      "url": "https://github.com/microsoft/playwright-mcp",
      "risk": "Low — sandboxed browser; first run downloads ~170MB Chromium. It can submit forms if told to.",
      "verdict": "The runtime-verification workhorse.",
      "pop": "⭐34k · Microsoft-official · loved",
      "popRank": 5
    },
    {
      "id": "mcp-fetch",
      "name": "Fetch MCP (official)",
      "aisle": "foundations",
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Fetches a URL and converts it to clean markdown for Claude.",
      "why": "Lightweight way to read docs/specs/pages during work without a heavier browser tool.",
      "maturity": "Official MCP reference server, MIT, active.",
      "install": "claude mcp add fetch -- uvx mcp-server-fetch",
      "url": "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
      "risk": "Low — outbound HTTP only; respects robots.txt by default.",
      "verdict": "Cheap, useful, safe.",
      "pop": "⭐87k (MCP monorepo) · official · widely used",
      "popRank": 4
    },
    {
      "id": "mcp-memory",
      "name": "Memory / Knowledge Graph MCP (official)",
      "aisle": "foundations",
      "also": [
        "data"
      ],
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Persistent cross-session knowledge graph stored locally as a JSONL file (entities, relations, observations).",
      "why": "A lightweight programmatic memory layer that complements CLAUDE.md and your Obsidian vault.",
      "maturity": "Official MCP reference server, MIT, active.",
      "install": "claude mcp add memory -- npx -y @modelcontextprotocol/server-memory",
      "url": "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
      "risk": "Low — stays on your machine.",
      "verdict": "Pairs well with CLAUDE.md.",
      "pop": "⭐87k (MCP monorepo) · ~45k npm dl/wk · official",
      "popRank": 4
    },
    {
      "id": "mcp-seqthinking",
      "name": "Sequential Thinking MCP (official)",
      "aisle": "foundations",
      "also": [
        "orchestration",
        "planning"
      ],
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Structures Claude's reasoning into explicit, revisable, branchable steps before it answers.",
      "why": "Great for genuinely ambiguous architecture/debugging calls on a large codebase. Produces an auditable reasoning chain.",
      "maturity": "Official MCP reference server, MIT, active.",
      "install": "claude mcp add sequential-thinking -- npx -y @modelcontextprotocol/server-sequential-thinking",
      "url": "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
      "risk": "Low — pure reasoning scaffold, no file access.",
      "verdict": "Use for high-uncertainty design questions.",
      "pop": "⭐87k (MCP monorepo) · ~72k npm dl/wk · official",
      "popRank": 4
    },
    {
      "id": "mcp-time",
      "name": "Time MCP (official)",
      "aisle": "foundations",
      "type": "MCP server",
      "tier": "Situational",
      "cost": "Free",
      "what": "Gives Claude accurate current time and timezone conversions.",
      "why": "Claude has no clock; handy for scheduling, logging, or time-aware code.",
      "maturity": "Official MCP reference server, MIT.",
      "install": "claude mcp add time -- uvx mcp-server-time",
      "url": "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
      "risk": "Low.",
      "verdict": "Tiny, zero-risk, occasionally essential.",
      "pop": "⭐87k (MCP monorepo) · official utility",
      "popRank": 3
    },
    {
      "id": "dbhub",
      "name": "DBHub (Bytebase)",
      "aisle": "foundations",
      "also": [
        "data"
      ],
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "what": "One MCP server for SQLite, Postgres, MySQL, MariaDB and SQL Server behind a single interface, with a read-only mode.",
      "why": "The maintained replacement for the official SQLite/Postgres reference servers (which were archived with SQL-injection issues). One install covers your whole SQLite→Postgres journey.",
      "maturity": "Bytebase, MIT, actively maintained.",
      "install": "claude mcp add dbhub -- npx -y @bytebase/dbhub --transport stdio --dsn \"sqlite:///C:/path/to/db.sqlite\"",
      "url": "https://github.com/bytebase/dbhub",
      "risk": "Low — use read-only mode unless you explicitly need writes.",
      "verdict": "Use this instead of the archived official DB servers.",
      "pop": "⭐2.9k · Bytebase · multi-DB · actively maintained",
      "popRank": 3
    },
    {
      "id": "obsidian-mcp",
      "name": "Obsidian MCP (Local REST API + cyanheads)",
      "aisle": "foundations",
      "also": [
        "data",
        "pm"
      ],
      "type": "MCP server",
      "tier": "Situational",
      "cost": "Free",
      "what": "Read, write, search and edit your Obsidian vault notes/tags/frontmatter from Claude Code, via the Obsidian \"Local REST API\" plugin.",
      "why": "Your PKB is the source of truth for project context — this flows planning notes and specs straight into coding sessions, no copy-paste.",
      "maturity": "cyanheads/obsidian-mcp-server, Apache-2.0, the best-maintained Obsidian option in 2026 (most others are abandoned).",
      "install": "In Obsidian install the \"Local REST API\" plugin and copy its token. Then add cyanheads/obsidian-mcp-server with that token — see the repo.",
      "url": "https://github.com/cyanheads/obsidian-mcp-server",
      "risk": "Medium — exposes the vault over localhost with a bearer token. Keep the port localhost-only; scope to specific folders. Was stale in late 2025 then revived; small audience.",
      "verdict": "Best Obsidian MCP option, but niche — scope it to specific folders.",
      "pop": "⭐577 · niche · was stale, recently revived",
      "popRank": 2
    },
    {
      "id": "anthropic-skills",
      "name": "Anthropic Official Skills (PDF/Word/Excel/PPT…)",
      "aisle": "foundations",
      "also": [
        "docs",
        "data"
      ],
      "type": "Agent Skill",
      "tier": "Core",
      "cost": "Free",
      "what": "Official SKILL.md packs that let Claude create, read, edit and extract data from PDF, Word, PowerPoint and Excel files.",
      "why": "Covers the whole office-document surface for free, working inside sessions you already have open.",
      "maturity": "Official Anthropic skills repo, very widely used.",
      "install": "Copy the skill folders from the repo into %USERPROFILE%\\.claude\\skills\\ (or install via the official plugin marketplace).",
      "url": "https://github.com/anthropics/skills",
      "risk": "Low — document skills may need python-docx/openpyxl available; install once.",
      "verdict": "The \"handle any document\" backbone.",
      "pop": "⭐147k · Anthropic-official · loved",
      "popRank": 5
    },
    {
      "id": "plugin-marketplace",
      "name": "Skills + Official Plugin Marketplace",
      "aisle": "foundations",
      "also": [
        "orchestration"
      ],
      "type": "Claude Code Plugin",
      "tier": "Core",
      "cost": "Free",
      "what": "The built-in marketplace + the skill system. Install bundles of commands/subagents/hooks/MCP with one command.",
      "why": "Beginner-friendly on-ramp: adopt a vetted workflow without writing anything. Stick to the official marketplace.",
      "maturity": "Official Anthropic; community marketplace is screened but third-party.",
      "install": "In Claude Code run /plugin to browse, e.g. /plugin install <name>@claude-plugins-official",
      "url": "https://code.claude.com/docs/en/discover-plugins",
      "risk": "Low for official; treat third-party marketplaces with G3 caution.",
      "verdict": "Your gateway to packaged workflows.",
      "pop": "Official + community marketplaces · growing fast",
      "popRank": 4
    },
    {
      "id": "awesome-claude-code",
      "name": "awesome-claude-code (discovery hub)",
      "aisle": "foundations",
      "also": [
        "orchestration"
      ],
      "type": "Concept",
      "tier": "Recommended",
      "cost": "Free",
      "what": "A community-curated catalog of hooks, skills, slash commands, subagents and patterns for Claude Code.",
      "why": "Your single best \"what have others built?\" reference when restocking — but run anything you find through the Protocol.",
      "maturity": "Community, very large following, frequently updated.",
      "install": "Browse on GitHub; copy patterns you need. No install.",
      "url": "https://github.com/hesreallyhim/awesome-claude-code",
      "risk": "Low — it's a list; vet each linked item itself.",
      "verdict": "Discovery hub, not an auto-add.",
      "pop": "⭐46k · community discovery hub · active",
      "popRank": 4
    },
    {
      "id": "subagents",
      "name": "Subagents",
      "aisle": "orchestration",
      "type": "Subagent",
      "tier": "Core",
      "cost": "Free",
      "what": "Specialized Claude instances with their own context window and tools, spawned to handle a focused sub-task and report a summary back.",
      "why": "This is your \"callers that call other tools.\" Keeps the main context clean; route \"read the whole repo and find X\" to a subagent. (It's how this whole catalog was researched — parallel subagents.)",
      "maturity": "Official Anthropic feature.",
      "install": "Create .claude/agents/<name>.md with a system prompt + allowed-tools. Built in — no package.",
      "url": "https://code.claude.com/docs/en/sub-agents",
      "risk": "Low — each has its own permission scope.",
      "verdict": "Core orchestration primitive.",
      "pop": "Built-in · loved",
      "popRank": 5
    },
    {
      "id": "hooks",
      "name": "Hooks",
      "aisle": "orchestration",
      "also": [
        "security",
        "verification"
      ],
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "Commands that fire automatically on events (PreToolUse, PostToolUse, SessionStart, Stop) — deterministic guardrails, not AI guesses.",
      "why": "Auto-format on edit, block changes to .env, run a secret scan after writes. Enforce quality/safety every time, guaranteed.",
      "maturity": "Official Anthropic feature.",
      "install": "Add a hooks block to .claude/settings.json (see starter-kit/). Use /hooks or the update-config skill to write it correctly.",
      "url": "https://code.claude.com/docs/en/hooks",
      "risk": "Low — hooks run with your privileges; review any community hook first.",
      "verdict": "Your automatic safety net.",
      "pop": "Built-in · loved",
      "popRank": 4
    },
    {
      "id": "plan-mode",
      "name": "Plan Mode",
      "aisle": "orchestration",
      "also": [
        "planning"
      ],
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "A read-only mode where Claude researches and proposes a full plan before touching any code; you approve before edits happen.",
      "why": "Measure twice, cut once. The cheapest place to catch an expensive mistake on a big codebase is in the plan.",
      "maturity": "Official Anthropic feature (paid Claude plans).",
      "install": "Press Shift+Tab to cycle into Plan Mode in any Claude Code session.",
      "url": "https://code.claude.com/docs/en/how-claude-code-works",
      "risk": "Low — back up important plans into the repo.",
      "verdict": "Use before every non-trivial change.",
      "pop": "Built-in · one of the most-cited features · loved",
      "popRank": 5
    },
    {
      "id": "spec-kit",
      "name": "GitHub Spec Kit",
      "aisle": "orchestration",
      "also": [
        "planning"
      ],
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Spec-driven development: adds /speckit.specify, .plan, .tasks, .implement commands that turn a vague idea into an executable spec + task list before code.",
      "why": "Tames \"vibe coding\" chaos on large projects; the task units survive context resets and map to your idea→production stages.",
      "maturity": "Official GitHub org, very popular, MIT — still pre-1.0 (pin a version).",
      "install": "uv tool install specify-cli --from git+https://github.com/github/spec-kit.git",
      "url": "https://github.com/github/spec-kit",
      "risk": "Low — writes markdown, no execution. Conventions still evolving; pin a tag.",
      "verdict": "The most legit free spec workflow.",
      "pop": "⭐109k · GitHub-official · positive",
      "popRank": 5
    },
    {
      "id": "deep-research",
      "name": "Deep Research / Dynamic Workflows",
      "aisle": "orchestration",
      "also": [
        "planning"
      ],
      "type": "Agent Skill",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Multi-agent research from inside Claude Code — an orchestrator fans out parallel subagents to search, verify and synthesize a cited report.",
      "why": "Research a library, competitor or pattern without leaving Claude Code, landing findings into a spec or CLAUDE.md.",
      "maturity": "Official Anthropic (paid Claude plans).",
      "install": "Built in. Use the /deep-research skill; enable Dynamic Workflows in settings if needed.",
      "url": "https://www.anthropic.com/claude-code",
      "risk": "Low — verify accuracy-critical findings yourself.",
      "verdict": "Planning-stage power tool.",
      "pop": "Built-in (research preview) · loved",
      "popRank": 4
    },
    {
      "id": "code-review-skills",
      "name": "/code-review + /security-review (built-in)",
      "aisle": "verification",
      "also": [
        "security"
      ],
      "type": "Agent Skill",
      "tier": "Core",
      "cost": "Free",
      "what": "Built-in Claude Code skills that review your current diff for bugs/simplifications (/code-review) or vulnerabilities (/security-review). --fix applies fixes; --comment posts to a PR.",
      "why": "Highest ROI, zero install, zero extra cost. Run them on every feature branch.",
      "maturity": "Official Anthropic, ships with Claude Code.",
      "install": "Just type /code-review or /security-review in a session.",
      "url": "https://code.claude.com/docs/en/claude-code",
      "risk": "Low — LLM review; verify findings. Not a replacement for deterministic scanners.",
      "verdict": "Use constantly. Free.",
      "pop": "Built-in · loved",
      "popRank": 5
    },
    {
      "id": "verify-skill",
      "name": "/verify (built-in)",
      "aisle": "verification",
      "type": "Agent Skill",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Built-in skill that runs your app and observes real behavior to confirm a change actually does what it should.",
      "why": "Closes the gap between \"tests pass\" and \"the feature works.\" Pairs with Playwright MCP for UI.",
      "maturity": "Official Anthropic, ships with Claude Code.",
      "install": "Type /verify in a session.",
      "url": "https://code.claude.com/docs/en/claude-code",
      "risk": "Low.",
      "verdict": "Confirm before you ship.",
      "pop": "Built-in · positive",
      "popRank": 4
    },
    {
      "id": "pre-commit",
      "name": "pre-commit framework",
      "aisle": "verification",
      "also": [
        "security",
        "optimization"
      ],
      "type": "Hook",
      "tier": "Core",
      "cost": "Free",
      "what": "A language-agnostic framework that runs any linter/formatter/scanner automatically on every git commit, from one config file.",
      "why": "The glue that makes every other CLI tool (Semgrep, Ruff, secret scanners, audits) run automatically — you never ship broken code by accident.",
      "maturity": "pre-commit/pre-commit, very widely used, MIT, mature.",
      "install": "pip install pre-commit  then  pre-commit install  (config in .pre-commit-config.yaml — template in starter-kit/)",
      "url": "https://github.com/pre-commit/pre-commit",
      "risk": "Low — quote paths in PowerShell.",
      "verdict": "Install once per repo; everything else rides on it.",
      "pop": "⭐15k · ~34M dl/wk · de-facto standard · loved",
      "popRank": 5
    },
    {
      "id": "pytest-cov",
      "name": "pytest-cov + coverage.py",
      "aisle": "verification",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Measures statement/branch test coverage and fails CI below a threshold.",
      "why": "For a big codebase, knowing which branches are untested is table stakes before shipping.",
      "maturity": "pytest-dev / coverage.py — the de-facto Python standard, decades of maintenance.",
      "install": "pip install pytest-cov  then  pytest --cov=src --cov-fail-under=80",
      "url": "https://github.com/pytest-dev/pytest-cov",
      "risk": "Low — phase thresholds in gradually on legacy code.",
      "verdict": "Standard for production Python.",
      "pop": "⭐2k · ~40M dl/wk · ubiquitous in CI · loved",
      "popRank": 5
    },
    {
      "id": "mutmut",
      "name": "mutmut (mutation testing)",
      "aisle": "verification",
      "type": "CLI tool",
      "tier": "Shortlist",
      "cost": "Free",
      "what": "Mutates your code and checks whether your tests catch each change — reveals \"green but worthless\" tests.",
      "why": "Coverage proves lines ran, not that tests are meaningful. Mutation testing proves the latter.",
      "maturity": "boxed/mutmut, actively used, MIT.",
      "install": "pip install mutmut  then  mutmut run  (needs WSL on Windows — fork() requirement)",
      "url": "https://github.com/boxed/mutmut",
      "risk": "Requires WSL on Windows; slow — run on critical modules only.",
      "verdict": "Shortlist for you (WSL dependency). Great concept.",
      "pop": "⭐1.3k · niche (reference mutation tester)",
      "popRank": 2
    },
    {
      "id": "semgrep",
      "name": "Semgrep CE (+ Claude Code plugin)",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Core",
      "cost": "Free",
      "costNote": "CE free; cloud free up to 10 contributors",
      "what": "Fast multi-language static security analysis (SAST) with 3,000+ community rules. The official plugin auto-scans every file Claude writes via a hook.",
      "why": "Catches injection, XSS, crypto misuse and hardcoded creds the moment Claude generates code. 30+ languages.",
      "maturity": "Semgrep Inc., very widely used, LGPL-2.1 CE, active.",
      "install": "pip install semgrep (CLI). Plugin: /plugin install from the marketplace. MCP: claude mcp add semgrep -- uvx semgrep-mcp",
      "url": "https://github.com/semgrep/semgrep",
      "risk": "Low — CE lacks cross-file dataflow (a Pro feature). Use the plugin or binary; the old standalone MCP repo is archived. CE lacks cross-file taint analysis (paywalled to Pro; the OpenGrep fork restores it) — ~48% vs ~72% detection on benchmarks.",
      "verdict": "The single most important free SAST for Claude Code.",
      "pop": "⭐15k · very active · note CE limits below",
      "popRank": 4
    },
    {
      "id": "betterleaks",
      "name": "Betterleaks (gitleaks successor)",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Shortlist",
      "cost": "Free",
      "what": "Detects and validates hardcoded secrets in repos/dirs/archives; higher recall than entropy-based scanners.",
      "why": "Built by gitleaks' original creator after he lost control of the gitleaks repo; MIT, backed by Aikido, multi-maintainer for stability.",
      "maturity": "betterleaks/betterleaks, shipped 1.0 in 2026, MIT, active.",
      "install": "Download the binary from the repo; a pre-commit hook is available.",
      "url": "https://github.com/betterleaks/betterleaks",
      "risk": "Low — young but well-backed; watch it mature (Rule R3). Very new (launched 2026) — promising but unproven; watch it mature.",
      "verdict": "Shortlist — promising successor from gitleaks' creator, but only months old.",
      "pop": "⭐1.1k · new (2026) · by gitleaks' creator · watch",
      "popRank": 2
    },
    {
      "id": "gitleaks",
      "name": "gitleaks",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "The long-standing secret scanner for git history and staged files (regex + entropy, 160+ patterns).",
      "why": "Battle-tested and still works fine as a pre-commit gate. Listed alongside Betterleaks while the governance split settles.",
      "maturity": "gitleaks/gitleaks, very widely used, MIT — but the creator left for Betterleaks.",
      "install": "winget install gitleaks  (or add the gitleaks pre-commit hook)",
      "url": "https://github.com/gitleaks/gitleaks",
      "risk": "Low — governance uncertainty after the maintainer split; functional today. Governance uncertain: the original creator left in 2026 and launched Betterleaks; still works well today.",
      "verdict": "Solid today; watch the Betterleaks transition.",
      "pop": "⭐27k · industry standard · ⚠ creator left → governance watch",
      "popRank": 5
    },
    {
      "id": "trufflehog",
      "name": "TruffleHog",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Core",
      "cost": "Free",
      "what": "Finds and verifies 800+ secret types across git/S3/Docker — actively confirms whether a found secret is still live.",
      "why": "Complements a fast pre-commit scanner: use it for deep, low-false-positive periodic scans of full history.",
      "maturity": "Truffle Security, very widely used, AGPL-3.0 core.",
      "install": "winget install TruffleSecurity.TruffleHog  (or docker run trufflesecurity/trufflehog ...)",
      "url": "https://github.com/trufflesecurity/trufflehog",
      "risk": "Low — AGPL (review for your project); live verification makes network calls.",
      "verdict": "Core secret scanner — most proven and actively maintained of the bunch.",
      "pop": "⭐26k · verifies live secrets · loved",
      "popRank": 5
    },
    {
      "id": "grype",
      "name": "Grype (Anchore)",
      "aisle": "security",
      "also": [
        "compliance"
      ],
      "type": "CLI tool",
      "tier": "Core",
      "cost": "Free",
      "what": "Vulnerability scanner for filesystems, container images and SBOMs across 20+ ecosystems.",
      "why": "Your default dependency/CVE scanner — and the safer pick over Trivy after Trivy's 2026 supply-chain incident. Pairs with Syft.",
      "maturity": "Anchore, widely used, Apache-2.0, very active.",
      "install": "winget install Anchore.Grype  then  grype dir:.",
      "url": "https://github.com/anchore/grype",
      "risk": "Low.",
      "verdict": "Preferred CVE scanner (no Trivy drama).",
      "pop": "⭐12k · Anchore · pairs with Syft · very active",
      "popRank": 4
    },
    {
      "id": "syft",
      "name": "Syft (Anchore)",
      "aisle": "security",
      "also": [
        "compliance"
      ],
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Generates a Software Bill of Materials (SPDX/CycloneDX) from a project or image. Fully offline, no account.",
      "why": "SBOMs are increasingly required by enterprise/government buyers. Syft + Grype = a complete free SBOM→CVE pipeline.",
      "maturity": "Anchore, widely used, Apache-2.0, active.",
      "install": "scoop install syft  then  syft dir:. -o spdx-json=sbom.json",
      "url": "https://github.com/anchore/syft",
      "risk": "Low — accuracy depends on lockfiles being present.",
      "verdict": "Essential if you'll sell to enterprises.",
      "pop": "⭐9k · Anchore SBOM · very active",
      "popRank": 4
    },
    {
      "id": "trivy",
      "name": "Trivy",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Shortlist",
      "cost": "Free",
      "what": "All-in-one scanner: images, filesystems, IaC, SBOM, secrets, licenses.",
      "why": "The most capable free all-in-one — but its trivy-action/setup-trivy were compromised in a March 2026 supply-chain attack.",
      "maturity": "Aqua Security, very widely used, Apache-2.0.",
      "install": "winget install AquaSecurity.Trivy — and PIN any GitHub Action to a full commit SHA, not a tag. Read the advisory first.",
      "url": "https://github.com/aquasecurity/trivy/security/advisories/GHSA-69fq-xp46-6x23",
      "risk": "Historical supply-chain compromise. Prefer Grype+Syft; if you use Trivy, pin SHAs and verify a clean build.",
      "verdict": "Shortlist — capable, but demoted from Core after the incident.",
      "pop": "⭐35k · capable, but ⚠ Mar-2026 supply-chain compromise — pin SHAs",
      "popRank": 5
    },
    {
      "id": "osv-scanner",
      "name": "OSV-Scanner (Google)",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Google's frontend to the OSV vulnerability database — scans lockfiles/SBOMs across Python, Node, Go, Rust, Java at once.",
      "why": "Authoritative, polyglot, no API key. Great single-command SCA on a multi-language repo.",
      "maturity": "Google, widely used, Apache-2.0.",
      "install": "Download the binary (or go install github.com/google/osv-scanner/v2/cmd/osv-scanner@latest); a pre-commit hook exists.",
      "url": "https://github.com/google/osv-scanner",
      "risk": "Low — less deep than language-specific tools on edge cases.",
      "verdict": "Best free polyglot lockfile scanner.",
      "pop": "⭐10k · Google · OSV.dev · active",
      "popRank": 4
    },
    {
      "id": "bandit",
      "name": "Bandit",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "costNote": "Python only",
      "what": "Python-only SAST: AST-level checks for hardcoded passwords, weak crypto, insecure deserialization, subprocess injection.",
      "why": "Fast, zero-config, a non-negotiable pre-commit hook for any Python code.",
      "maturity": "PyCQA, very widely used, Apache-2.0.",
      "install": "pip install bandit  then  bandit -r src/  (or add the pre-commit hook)",
      "url": "https://github.com/PyCQA/bandit",
      "risk": "Low — tune false positives on subprocess via .bandit config.",
      "verdict": "Mandatory for Python.",
      "pop": "⭐8k · ~1.7M dl/wk · PyCQA standard (Python)",
      "popRank": 4
    },
    {
      "id": "eslint-security",
      "name": "eslint-plugin-security",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Situational",
      "cost": "Free",
      "costNote": "JS/Node only",
      "what": "ESLint rules for Node/JS security issues (unsafe eval/exec, ReDoS, path traversal).",
      "why": "Runs inside your existing ESLint pipeline — zero extra tooling for JS projects.",
      "maturity": "eslint-community, maintained, Apache-2.0.",
      "install": "npm i -D eslint-plugin-security  then extend plugin:security/recommended in your ESLint config.",
      "url": "https://github.com/eslint-community/eslint-plugin-security",
      "risk": "Low — JS only; not a replacement for Semgrep. Thin rule set (~13 rules) misses most modern JS vulns — use as one layer, not a complete linter.",
      "verdict": "Situational — a baseline JS lint layer; pair with Semgrep, don't rely on it alone.",
      "pop": "⭐2.4k · ~2M dl/wk · ⚠ thin coverage (~13 rules)",
      "popRank": 3
    },
    {
      "id": "pip-audit",
      "name": "pip-audit",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "costNote": "Python only",
      "what": "Official PyPA tool auditing Python environments/requirements against the OSV advisory DB; can auto-fix by upgrading.",
      "why": "One line, official backing, better Python-specific signal than generic polyglot tools.",
      "maturity": "PyPA + Trail of Bits, active, Apache-2.0.",
      "install": "pip install pip-audit  then  pip-audit",
      "url": "https://github.com/pypa/pip-audit",
      "risk": "Low — needs internet for DB queries.",
      "verdict": "Pair with OSV-Scanner for full Python coverage.",
      "pop": "⭐1.3k · ~4.3M dl/wk · official PyPA",
      "popRank": 4
    },
    {
      "id": "snyk",
      "name": "Snyk CLI",
      "aisle": "security",
      "type": "CLI tool",
      "tier": "Shortlist",
      "cost": "Free tier",
      "costNote": "private repos: ~400 OSS + 100 SAST tests/mo",
      "what": "Polished SCA + SAST + container scanning with a dashboard and IDE integrations.",
      "why": "Useful as a second-opinion scanner with nice reporting; free tier may suffice if you manage scan frequency.",
      "maturity": "Snyk, industry-standard, stable.",
      "install": "npm install -g snyk  then  snyk auth  then  snyk test",
      "url": "https://snyk.io/plans/",
      "risk": "Test limits burn fast in CI on private repos; data leaves your machine to Snyk's cloud. 2026 credit-based pricing adds complexity.",
      "verdict": "Shortlist — primary scanning is covered free by OSV-Scanner + pip-audit + Grype.",
      "pop": "Industry leader · free tier limited · ⚠ pricing complexity",
      "popRank": 4
    },
    {
      "id": "scorecard",
      "name": "OpenSSF Scorecard",
      "aisle": "security",
      "also": [
        "compliance"
      ],
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Scores a repo across 18+ security-health checks: branch protection, pinned deps, SAST in CI, signed releases, etc.",
      "why": "Instantly audits your repo's hygiene against industry norms; each failing check is an actionable fix.",
      "maturity": "OpenSSF (Linux Foundation), Apache-2.0, active.",
      "install": "Run via the binary/Action: scorecard --repo github.com/you/repo  (or use the GitHub Action)",
      "url": "https://github.com/ossf/scorecard",
      "risk": "Low — private repos need a read-scope token.",
      "verdict": "Measures whether your repo practices what the tools preach.",
      "pop": "⭐5.5k · OpenSSF/CISA-endorsed · active",
      "popRank": 4
    },
    {
      "id": "ruff",
      "name": "Ruff",
      "aisle": "optimization",
      "also": [
        "verification"
      ],
      "type": "CLI tool",
      "tier": "Core",
      "cost": "Free",
      "costNote": "Python",
      "what": "Rust-based Python linter + formatter that replaces Flake8, Black, isort, pyupgrade and more — 10–100x faster, 900+ rules.",
      "why": "Runs in milliseconds as a pre-commit + PostToolUse hook on every file Claude writes. Replaces a whole toolchain.",
      "maturity": "Astral, very widely used, MIT, professionally maintained.",
      "install": "pip install ruff  then  ruff check . && ruff format .",
      "url": "https://github.com/astral-sh/ruff",
      "risk": "Low — one config file to migrate from the old tools. Astral (maintainer) was acquired in 2026 — no issue today, but watch future stewardship.",
      "verdict": "Mandatory for Python. Nothing close on speed.",
      "pop": "⭐48k · most-admired tool (SO 2025) · loved",
      "popRank": 5
    },
    {
      "id": "radon",
      "name": "Radon",
      "aisle": "optimization",
      "type": "CLI tool",
      "tier": "Situational",
      "cost": "Free",
      "costNote": "Python",
      "what": "Python complexity metrics: cyclomatic complexity, maintainability index, raw LOC — flags the gnarliest functions.",
      "why": "Gives Claude a complexity map so refactoring targets the worst offenders first on a big codebase.",
      "maturity": "rubik/radon, stable (feature-complete), MIT.",
      "install": "pip install radon  then  radon cc src/ -a -nc",
      "url": "https://github.com/rubik/radon",
      "risk": "Low — Python only, infrequently updated.",
      "verdict": "Handy for targeted refactors.",
      "pop": "⭐2k · niche complexity metrics (fills a Ruff gap)",
      "popRank": 2
    },
    {
      "id": "lighthouse",
      "name": "Lighthouse / Lighthouse CI",
      "aisle": "optimization",
      "also": [
        "uiux"
      ],
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Google's audit for performance, accessibility, SEO and best practices; LHCI gates regressions in CI with budgets.",
      "why": "If there's any web frontend, this scores perf + a11y in one shot and Claude can act on the JSON.",
      "maturity": "Google Chrome team, very widely used, Apache-2.0.",
      "install": "npm i -g lighthouse  then  lighthouse http://localhost:3000 --output json   (CI: npm i -g @lhci/cli)",
      "url": "https://github.com/GoogleChrome/lighthouse",
      "risk": "Low — needs a running build to audit.",
      "verdict": "Default perf+a11y gate for web UIs.",
      "pop": "⭐30k · ~3.6M dl/wk · Google standard",
      "popRank": 5
    },
    {
      "id": "bundle-analyzer",
      "name": "Bundle analyzer (webpack / Vite)",
      "aisle": "optimization",
      "type": "CLI tool",
      "tier": "Situational",
      "cost": "Free",
      "what": "Interactive treemap of what's bloating your JS bundle (parsed/gzip/brotli sizes).",
      "why": "Finds heavy deps and dead code before production; hand the output to Claude to trim.",
      "maturity": "webpack team (and rollup-plugin-visualizer for Vite), widely used, MIT.",
      "install": "npm i -D webpack-bundle-analyzer  (Vite: npm i -D rollup-plugin-visualizer)",
      "url": "https://github.com/webpack/webpack-bundle-analyzer",
      "risk": "Low — pick the analyzer matching your bundler.",
      "verdict": "Indispensable for frontend perf work.",
      "pop": "⭐13k · ~7–11M dl/wk · (webpack-specific)",
      "popRank": 4
    },
    {
      "id": "tailwind",
      "name": "Tailwind CSS v4",
      "aisle": "uiux",
      "type": "CLI tool",
      "tier": "Core",
      "cost": "Free",
      "what": "Utility-first CSS framework; v4 is zero-config, single CSS import, dramatically faster builds.",
      "why": "The standard styling layer for modern HTML/PWA, and Claude writes it natively and well.",
      "maturity": "Tailwind Labs, very widely used, MIT.",
      "install": "npm install tailwindcss @tailwindcss/vite  (config is CSS-first in v4)",
      "url": "https://tailwindcss.com/",
      "risk": "Low — v4 config differs from v3; most guides have updated. 2026 reports of funding/staffing cuts at Tailwind Labs — watch long-term stewardship.",
      "verdict": "Foundation layer for your front-end.",
      "pop": "⭐95k · ~107M dl/wk · dominant · ⚠ 2026 funding cuts (watch)",
      "popRank": 5
    },
    {
      "id": "shadcn-mcp",
      "name": "shadcn/ui MCP + registry",
      "aisle": "uiux",
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Lets Claude browse, search and install shadcn/ui components into your project by natural language.",
      "why": "Huge time-saver for assembling polished, battle-tested components; Claude translates the React patterns to your stack.",
      "maturity": "Official shadcn, enormous ecosystem, MIT.",
      "install": "npx shadcn@latest mcp init --client claude",
      "url": "https://ui.shadcn.com/docs/mcp",
      "risk": "Low — components are React-first; for plain HTML you use the output CSS/classes.",
      "verdict": "A component catalog Claude can install from.",
      "pop": "⭐116k · most-starred component catalog · loved",
      "popRank": 5
    },
    {
      "id": "chrome-devtools-mcp",
      "name": "Chrome DevTools MCP (Google)",
      "aisle": "uiux",
      "also": [
        "verification",
        "optimization"
      ],
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Gives Claude the Chrome DevTools Protocol — network inspection, console, performance traces, screenshots.",
      "why": "Deeper perf/console debugging than Playwright alone; official Google project.",
      "maturity": "Official ChromeDevTools org, very widely used, Apache-2.0.",
      "install": "claude mcp add chrome-devtools -- npx -y chrome-devtools-mcp@latest",
      "url": "https://github.com/ChromeDevTools/chrome-devtools-mcp",
      "risk": "Low — needs Chrome installed; overlaps Playwright (add only for perf traces).",
      "verdict": "Adds performance insight Playwright lacks.",
      "pop": "⭐43k · Google-official · loved",
      "popRank": 5
    },
    {
      "id": "axe-cli",
      "name": "axe-core CLI (Deque)",
      "aisle": "uiux",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Runs Deque's axe accessibility engine against a URL from the command line (WCAG A/AA/AAA), with near-zero false positives.",
      "why": "Claude can run it and auto-fix the violations it reports. The best automatable a11y check.",
      "maturity": "Deque Labs, widely used in enterprise QA, MPL-2.0.",
      "install": "npm i -g @axe-core/cli  then  axe http://localhost:3000",
      "url": "https://github.com/dequelabs/axe-core-npm",
      "risk": "Low — automated checks catch ~30–40% of a11y issues (a known limit, not a flaw).",
      "verdict": "Automatable accessibility, Claude-friendly.",
      "pop": "axe-core ~18M dl/wk (1B+ total) · WCAG standard",
      "popRank": 5
    },
    {
      "id": "wave",
      "name": "WAVE (WebAIM)",
      "aisle": "uiux",
      "type": "Web service",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Browser extension that overlays accessibility errors, contrast failures, ARIA roles and heading structure on the page.",
      "why": "The fastest human-eye a11y review; install once, use on every page you build.",
      "maturity": "WebAIM (non-profit), maintained since 2001.",
      "install": "Install the \"WAVE Evaluation Tool\" from the Chrome/Edge/Firefox store.",
      "url": "https://wave.webaim.org/",
      "risk": "Low — one page at a time; not automatable (use axe for that).",
      "verdict": "Your manual visual a11y layer.",
      "pop": "WebAIM · 20+ yr track record · trusted",
      "popRank": 4
    },
    {
      "id": "storybook",
      "name": "Storybook",
      "aisle": "uiux",
      "type": "CLI tool",
      "tier": "Situational",
      "cost": "Free",
      "what": "A component workshop — build, document and visually test UI components in isolation, with auto-generated docs.",
      "why": "Lets you develop components without running the whole app; the docs double as a design-system reference.",
      "maturity": "Storybook org, very widely used (Shopify, GitLab…), MIT.",
      "install": "npx storybook@latest init",
      "url": "https://storybook.js.org/",
      "risk": "Low — heavyweight for tiny apps; worth it at ~10+ components.",
      "verdict": "Add when your component count grows.",
      "pop": "⭐90k · ~10–17M dl/wk · industry standard",
      "popRank": 5
    },
    {
      "id": "style-dictionary",
      "name": "Style Dictionary",
      "aisle": "uiux",
      "type": "CLI tool",
      "tier": "Situational",
      "cost": "Free",
      "what": "Turns one tokens.json (colors, spacing, fonts) into CSS variables, JS, iOS, Android — one source of truth.",
      "why": "Claude can author/update tokens and regenerate all your CSS variables consistently.",
      "maturity": "Tokens Studio maintainers, stable, Apache-2.0.",
      "install": "npm i -D style-dictionary  then  npx style-dictionary build",
      "url": "https://github.com/style-dictionary/style-dictionary",
      "risk": "Low — needs upfront token schema design.",
      "verdict": "For consistent design tokens.",
      "pop": "⭐4.7k · ~485k dl/wk · design-token standard",
      "popRank": 3
    },
    {
      "id": "figma-mcp",
      "name": "Figma Dev Mode MCP",
      "aisle": "uiux",
      "type": "MCP server",
      "tier": "Shortlist",
      "cost": "Free tier",
      "costNote": "~6 calls/mo free; practical use needs a paid Figma seat",
      "what": "Reads Figma frames/components/variables into code (and can write code→canvas).",
      "why": "Transformative design-to-code — paste a Figma URL, get accurate component code.",
      "maturity": "Official Figma, active.",
      "install": "Connect via figma.com / the Figma desktop app, then confirm with /mcp in Claude Code.",
      "url": "https://www.figma.com/blog/introducing-figma-mcp-server/",
      "risk": "Free tier (~6 calls/mo) is near-useless; needs a paid Figma seat to rely on.",
      "verdict": "Shortlist until you have a paid Figma seat.",
      "pop": "Figma-official · loved · (needs a paid seat)",
      "popRank": 4
    },
    {
      "id": "magic-mcp",
      "name": "21st.dev Magic MCP",
      "aisle": "uiux",
      "type": "MCP server",
      "tier": "Shortlist",
      "cost": "Free tier",
      "costNote": "~100 credits/mo",
      "what": "Generates polished React/Tailwind UI components on demand inside your editor (v0-like, via MCP).",
      "why": "Quick styled drafts for one-off components.",
      "maturity": "21st-dev, beta, active.",
      "install": "npx @21st-dev/magic@latest  (free account for an API key)",
      "url": "https://github.com/21st-dev/magic-mcp",
      "risk": "100 credits/mo is tight; React-first; beta API may change; cloud account required.",
      "verdict": "Light-use supplement, not a daily driver.",
      "pop": "⭐5k · 'v0 in your IDE' · early-stage (no releases)",
      "popRank": 3
    },
    {
      "id": "v0",
      "name": "v0 by Vercel",
      "aisle": "uiux",
      "type": "Web service",
      "tier": "Showroom",
      "cost": "Free tier",
      "costNote": "~$5/mo credits, burns fast; not a Claude integration",
      "what": "Browser AI UI generator (React/Tailwind) from prompts.",
      "why": "High-quality component scaffolding — but separate from Claude and credit-limited.",
      "maturity": "Vercel, established.",
      "install": "Use at v0.dev in the browser; paste output into your project.",
      "url": "https://v0.app/pricing",
      "risk": "Not integrated with Claude; free credits exhaust quickly; React-centric.",
      "verdict": "Showroom — use free credits deliberately, outside Claude.",
      "pop": "6M+ devs · Vercel · ⚠ free tier very limited",
      "popRank": 5
    },
    {
      "id": "mermaid",
      "name": "Mermaid (text-native diagrams)",
      "aisle": "visuals",
      "also": [
        "docs"
      ],
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "A text language for flowcharts, sequence, ER, Gantt, class and state diagrams that renders natively in GitHub, Obsidian and markdown.",
      "why": "Claude writes Mermaid directly — diagrams live next to your code/docs and stay in sync, zero tool call to create.",
      "maturity": "mermaid-js, very widely used, MIT.",
      "install": "No install for GitHub/Obsidian rendering. CLI export: npm i -g @mermaid-js/mermaid-cli",
      "url": "https://github.com/mermaid-js/mermaid",
      "risk": "Low — pure text, no lock-in.",
      "verdict": "Claude's native diagram language.",
      "pop": "⭐88.5k · the 'Markdown of diagrams' · loved",
      "popRank": 5
    },
    {
      "id": "mermaid-live",
      "name": "Mermaid Live Editor",
      "aisle": "visuals",
      "type": "Web service",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Official browser editor with live preview + PNG/SVG export. Paste Claude's Mermaid, tweak, export.",
      "why": "The fastest path from Claude text → a shareable diagram image for docs/decks.",
      "maturity": "Official mermaid-js project.",
      "install": "Open mermaid.live in a browser.",
      "url": "https://mermaid.live/",
      "risk": "Low — online; use mermaid-cli for offline export.",
      "verdict": "Zero-setup render+export.",
      "pop": "Official Mermaid playground · widely used",
      "popRank": 4
    },
    {
      "id": "drawio",
      "name": "draw.io / diagrams.net",
      "aisle": "visuals",
      "type": "Web service",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Free open-source diagramming app (offline Windows desktop available); flowcharts, ERDs, network, UML; exports SVG/PNG/XML.",
      "why": "Handles complex multi-node diagrams better than Mermaid; Claude can generate draw.io XML you open directly.",
      "maturity": "draw.io, huge user base, Apache-2.0.",
      "install": "Install \"draw.io Diagrams\" from the Microsoft Store, or use the web app.",
      "url": "https://www.drawio.com/",
      "risk": "Low — you open the XML in the app (Claude can't render it directly).",
      "verdict": "For richer, hand-arranged diagrams.",
      "pop": "Most popular OSS diagramming · ~88% satisfaction",
      "popRank": 5
    },
    {
      "id": "excalidraw",
      "name": "Excalidraw",
      "aisle": "visuals",
      "type": "Web service",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Browser whiteboard for hand-drawn-style sketches and wireframes; no account; exports PNG/SVG.",
      "why": "Zero-friction rough architecture/wireframe sketching; the hand-drawn look signals \"draft,\" not \"final.\"",
      "maturity": "Excalidraw, very widely used, MIT.",
      "install": "Open excalidraw.com.",
      "url": "https://excalidraw.com/",
      "risk": "Low — a human sketching tool, not Claude-generated output.",
      "verdict": "Fast wireframing companion to Mermaid.",
      "pop": "⭐125k · 'best sketchpad on the internet' · loved",
      "popRank": 5
    },
    {
      "id": "plantuml",
      "name": "PlantUML",
      "aisle": "visuals",
      "type": "Concept",
      "tier": "Situational",
      "cost": "Free",
      "what": "Text-to-UML for every UML type, C4 architecture and big sequence diagrams; renders to PNG/SVG/PDF.",
      "why": "Use when Mermaid struggles — large sequence diagrams or formal C4 architecture.",
      "maturity": "plantuml.com, decades of development, active.",
      "install": "Use planttext.com online (no install), or npm i -g node-plantuml (needs Java).",
      "url": "https://plantuml.com/",
      "risk": "Low — local rendering needs Java; online renderer avoids it.",
      "verdict": "For complex/formal diagrams beyond Mermaid.",
      "pop": "⭐13k · formal UML / C4 standard · active",
      "popRank": 4
    },
    {
      "id": "canva",
      "name": "Canva MCP / Connector",
      "aisle": "creative",
      "type": "Connector",
      "tier": "Core",
      "cost": "Free tier",
      "costNote": "core free; resize/brand kit need Pro",
      "what": "Official Canva integration — generate designs from prompts, search/edit designs, export PDF/PNG/PPTX, manage assets — by natural language.",
      "why": "You already have it connected. Claude drafts a poster brief, calls generate-design, and hands you a Canva link to finish. Posters, social, decks.",
      "maturity": "Official Canva, active, 20+ tools.",
      "install": "Already connected in your Claude. Docs at canva.dev/docs/mcp.",
      "url": "https://www.canva.dev/docs/mcp/",
      "risk": "Low — AI output is a starting draft; premium elements/resize need Pro.",
      "verdict": "Your marketing/poster engine — already yours.",
      "pop": "Canva-official · 240M users · design-focused",
      "popRank": 4
    },
    {
      "id": "hf-images",
      "name": "Hugging Face MCP / Spaces (image gen)",
      "aisle": "creative",
      "also": [
        "data"
      ],
      "type": "MCP server",
      "tier": "Recommended",
      "cost": "Free",
      "costNote": "community GPU queue waits",
      "what": "Free AI image generation (FLUX.1, Stable Diffusion 3.5, Qwen-Image) via HF Spaces, from inside Claude Code or the browser.",
      "why": "The only fully-free image-gen path for marketing hero images. FLUX.1-schnell is commercially usable. Combine with Canva for text overlay.",
      "maturity": "Official Hugging Face; you already have HF connected.",
      "install": "Use the official HF MCP (npx @huggingface/mcp-server, needs HF_TOKEN), or just open a Space in the browser.",
      "url": "https://huggingface.co/spaces/black-forest-labs/FLUX.1-dev",
      "risk": "Low — queue waits (30–120s); check each model's license for commercial use.",
      "verdict": "Free image generation. Finish text/layout in Canva.",
      "pop": "FLUX.1 ~9.5k Space likes · free (rate-limited) · ⚠ dev license = non-commercial",
      "popRank": 4
    },
    {
      "id": "init",
      "name": "/init (CLAUDE.md generator)",
      "aisle": "docs",
      "also": [
        "foundations"
      ],
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "Built-in command that scans the project and generates/updates a CLAUDE.md.",
      "why": "Bootstraps new projects to your shared-context standard in seconds and keeps them current.",
      "maturity": "Official Anthropic, ships with Claude Code.",
      "install": "Run /init in any project.",
      "url": "https://code.claude.com/docs/en/memory",
      "risk": "Low — review and add the non-obvious rules it can't infer.",
      "verdict": "First command in any new repo.",
      "pop": "Built-in · widely used (keep CLAUDE.md fresh)",
      "popRank": 4
    },
    {
      "id": "mkdocs",
      "name": "MkDocs Material",
      "aisle": "docs",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free",
      "what": "Markdown → polished static docs site (search, versioning, admonitions, native diagrams). Deploys to GitHub Pages in minutes.",
      "why": "Best-in-class for Python-leaning and PKB-style docs; feature-complete and now fully free.",
      "maturity": "squidfunk/mkdocs-material, very widely used; in stable maintenance mode (bug/security fixes).",
      "install": "pip install mkdocs-material  then  mkdocs new .  then  mkdocs serve",
      "url": "https://github.com/squidfunk/mkdocs-material",
      "risk": "Low — maintenance mode means no new features (the set is already complete).",
      "verdict": "Default docs site generator.",
      "pop": "⭐27k · ~3.8M dl/wk · used by Google/AWS/K8s · loved",
      "popRank": 5
    },
    {
      "id": "docusaurus",
      "name": "Docusaurus",
      "aisle": "docs",
      "type": "CLI tool",
      "tier": "Situational",
      "cost": "Free",
      "what": "React-based docs site generator with MDX, versioning, i18n and a blog.",
      "why": "Pick over MkDocs when the project is JS/TS-heavy or needs versioned API docs.",
      "maturity": "Meta, very widely used, MIT, active.",
      "install": "npx create-docusaurus@latest my-docs classic",
      "url": "https://github.com/facebook/docusaurus",
      "risk": "Low — heavier (Node) than MkDocs; overkill for simple markdown.",
      "verdict": "For JS/TS projects or versioned docs.",
      "pop": "⭐65k · Meta · React docs standard · loved",
      "popRank": 5
    },
    {
      "id": "duckdb-mcp",
      "name": "DuckDB / MotherDuck MCP",
      "aisle": "data",
      "type": "MCP server",
      "tier": "Situational",
      "cost": "Free",
      "costNote": "local free; cloud has a free tier",
      "what": "Connects Claude to DuckDB for fast analytical SQL over CSV/Parquet/JSON, locally or in MotherDuck cloud.",
      "why": "Perfect for the data-wrangling/reporting stages without standing up Postgres.",
      "maturity": "Official MotherDuck, active.",
      "install": "uvx mcp-server-motherduck --db-path local  (no token needed for local-only)",
      "url": "https://github.com/motherduckdb/mcp-server-motherduck",
      "risk": "Low for local use; cloud adds a token.",
      "verdict": "Best free CSV/Parquet analytics for Claude.",
      "pop": "⭐490 · MotherDuck-official · niche but solid",
      "popRank": 3
    },
    {
      "id": "gdrive",
      "name": "Google Drive Connector",
      "aisle": "data",
      "type": "Connector",
      "tier": "Situational",
      "cost": "Free",
      "what": "Official Google Drive connector exposing Drive files, Docs and Sheets to Claude for read/write.",
      "why": "You already have it — covers the cloud-document layer alongside your local Obsidian PKB.",
      "maturity": "Official Google/Anthropic connector.",
      "install": "Already connected. Re-add via Settings → Connectors if needed.",
      "url": "https://support.anthropic.com/en/articles/connectors",
      "risk": "Low–medium — OAuth scopes grant broad Drive access; review them.",
      "verdict": "Already yours; use for cloud docs.",
      "pop": "Anthropic-official connector · read-only",
      "popRank": 3
    },
    {
      "id": "stage-gate",
      "name": "Idea→Production Stage Gates",
      "aisle": "planning",
      "type": "Concept",
      "tier": "Core",
      "cost": "Free",
      "what": "The repo's own workflow: Think → Plan → Demo → Prototype → MVP → Production, each with a \"you may not pass until…\" gate.",
      "why": "Stops you polishing a dead demo or shipping an unhardened prototype. Plan in prose before code.",
      "maturity": "This repo — see docs/WORKFLOW.md.",
      "install": "Read docs/WORKFLOW.md; drive it with the prompt at the bottom of that file.",
      "url": "docs/WORKFLOW.md",
      "risk": "Low.",
      "verdict": "Your pipeline discipline.",
      "pop": "Built into this repo (docs/WORKFLOW.md)",
      "popRank": 3
    },
    {
      "id": "github-projects",
      "name": "GitHub Projects",
      "aisle": "pm",
      "type": "Web service",
      "tier": "Core",
      "cost": "Free",
      "what": "Built-in kanban/table/roadmap linked natively to Issues and PRs; unlimited on the free tier.",
      "why": "You already live on GitHub — zero new tool/auth, Issues/PRs auto-populate, and your GitHub MCP can query/update it.",
      "maturity": "GitHub (Microsoft), used by millions, stable.",
      "install": "On any repo, open the Projects tab.",
      "url": "https://github.com/features/issues",
      "risk": "Low — GitHub lock-in (fine for a solo dev).",
      "verdict": "Your default, lowest-friction PM.",
      "pop": "180M+ GitHub users · free · (Projects still maturing)",
      "popRank": 5
    },
    {
      "id": "obsidian-kanban",
      "name": "Obsidian Kanban plugin",
      "aisle": "pm",
      "also": [
        "data"
      ],
      "type": "Claude Code Plugin",
      "tier": "Shortlist",
      "cost": "Free",
      "what": "Markdown-backed kanban boards inside your Obsidian vault — plain text, versionable, readable by Claude.",
      "why": "Keeps project status in the same vault Claude already reads via the Obsidian MCP, so planning + status share one context.",
      "maturity": "obsidian-community/obsidian-kanban, widely used, stable.",
      "install": "Obsidian → Settings → Community Plugins → search \"Kanban\" → Install.",
      "url": "https://github.com/obsidian-community/obsidian-kanban",
      "risk": "Low — community plugin; test before Obsidian major upgrades. No release in 12+ months and the maintainer is seeking help — works, but maintenance is in doubt.",
      "verdict": "Shortlist — maintenance in doubt; boards are plain markdown so low lock-in.",
      "pop": "⭐4.3k · ⚠ no release 12+ mo · seeking maintainers",
      "popRank": 2
    },
    {
      "id": "linear",
      "name": "Linear (free tier)",
      "aisle": "pm",
      "type": "Web service",
      "tier": "Shortlist",
      "cost": "Free tier",
      "costNote": "hard cap ~250 issues",
      "what": "Fast, keyboard-driven issue tracker with cycles, triage and GitHub integration.",
      "why": "Best-in-class UX if you outgrow GitHub Projects.",
      "maturity": "Linear, battle-tested, active.",
      "install": "Sign up at linear.app and connect your GitHub repo.",
      "url": "https://linear.app/pricing",
      "risk": "The ~250-issue cap is a real constraint on a long-lived project.",
      "verdict": "Shortlist — great UX, but the cap pushes you to GitHub Projects for free.",
      "pop": "25k+ companies (OpenAI/Ramp) · loved · ⚠ free cap 250 issues",
      "popRank": 4
    },
    {
      "id": "notion",
      "name": "Notion (free + MCP)",
      "aisle": "pm",
      "also": [
        "docs"
      ],
      "type": "Connector",
      "tier": "Shortlist",
      "cost": "Free tier",
      "what": "All-in-one notes/wiki/kanban/db with an official MCP Claude can read/write.",
      "why": "Good if you want one tool for PKB + PM — but you already invest in Obsidian.",
      "maturity": "Official Notion MCP, stable.",
      "install": "claude mcp add notion -- npx -y @notionhq/notion-mcp-server  (needs a Notion API key)",
      "url": "https://github.com/makenotion/notion-mcp-server",
      "risk": "Low — running both Notion and Obsidian fragments your context. The official MCP has open stability/security issues; the hosted remote server is more reliable than self-hosted.",
      "verdict": "Shortlist — redundant with Obsidian unless you migrate.",
      "pop": "⭐4.4k · official MCP · ⚠ stability/security issues",
      "popRank": 4
    },
    {
      "id": "prompt-improver",
      "name": "Anthropic Prompt Generator + Improver",
      "aisle": "prompting",
      "type": "Web service",
      "tier": "Core",
      "cost": "Free",
      "costNote": "free account; small API token cost",
      "what": "Two in-browser tools in the Anthropic Console: generate a production-ready prompt from a goal, or improve an existing prompt with chain-of-thought + structure.",
      "why": "The authoritative first stop before writing any reusable prompt or a brief you'll hand to another person/AI.",
      "maturity": "Official Anthropic, production feature.",
      "install": "Open console.anthropic.com → Generate/Improve prompt.",
      "url": "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prompt-improver",
      "risk": "Low — output is Claude-optimized; light edits if handing to other models.",
      "verdict": "Use before crafting any meta-prompt.",
      "pop": "Anthropic-official · +30% prompt quality reported · loved",
      "popRank": 4
    },
    {
      "id": "metaprompt",
      "name": "Anthropic Metaprompt (cookbook)",
      "aisle": "prompting",
      "type": "Concept",
      "tier": "Recommended",
      "cost": "Free",
      "what": "An open-source \"prompt that writes prompts\" — give it a task, get a full production-quality prompt for that task.",
      "why": "Spin up reusable creative briefs (poster copy, social captions, build specs) to delegate to people or AIs.",
      "maturity": "Official Anthropic Cookbook, MIT.",
      "install": "Copy the metaprompt from the cookbook; use it as a skill or system prompt.",
      "url": "https://github.com/anthropics/anthropic-cookbook/blob/main/misc/metaprompt.ipynb",
      "risk": "Low — a pattern; quality tracks your task description.",
      "verdict": "Reusable brief generator.",
      "pop": "In anthropic-cookbook (⭐45k) · official pattern",
      "popRank": 4
    },
    {
      "id": "prompt-skills",
      "name": "Prompt skills as slash commands",
      "aisle": "prompting",
      "also": [
        "foundations"
      ],
      "type": "Agent Skill",
      "tier": "Core",
      "cost": "Free",
      "what": "Encode your best prompts as SKILL.md files (e.g. /write-spec, /create-handoff-prompt, /generate-prd) that auto-load and survive context resets.",
      "why": "Turn one-off prompt wins into durable, shareable, repeatable workflows across all your projects.",
      "maturity": "Official Anthropic skill system.",
      "install": "Create .claude/skills/<name>/SKILL.md with YAML frontmatter + instructions (see starter-kit/skills/).",
      "url": "https://code.claude.com/docs/en/skills",
      "risk": "Low — plain markdown, no execution.",
      "verdict": "Bank your prompt engineering as reusable skills.",
      "pop": "Built-in skill system · power-user favorite",
      "popRank": 4
    },
    {
      "id": "fossa",
      "name": "FOSSA CLI (license compliance)",
      "aisle": "compliance",
      "type": "CLI tool",
      "tier": "Recommended",
      "cost": "Free tier",
      "costNote": "unlimited scans, 5 projects",
      "what": "Scans dependencies for license types and flags GPL/AGPL/SSPL conflicts with your project's license; generates attribution reports.",
      "why": "License conflicts are the quiet compliance failure that kills enterprise deals. The free tier covers a solo dev.",
      "maturity": "FOSSA Inc., professional, well-documented.",
      "install": "PowerShell: iwr -useb https://raw.githubusercontent.com/fossas/fossa-cli/master/install.ps1 | iex  then  fossa analyze",
      "url": "https://github.com/fossas/fossa-cli",
      "risk": "Low — FOSSA cloud receives dependency metadata; review the privacy policy.",
      "verdict": "Covers the license gap SAST tools miss.",
      "pop": "⭐1.5k · used by Uber/Atlassian · 99.8% license accuracy",
      "popRank": 3
    },
    {
      "id": "openssf-badge",
      "name": "OpenSSF Best Practices Badge",
      "aisle": "compliance",
      "type": "Web service",
      "tier": "Recommended",
      "cost": "Free",
      "what": "A free self-assessment (Passing/Silver/Gold) over 65+ security best practices — a structured checklist recognized by enterprise buyers.",
      "why": "Earning a Passing badge maps directly to SOC 2 / ISO control areas and doubles as a public trust signal in your README.",
      "maturity": "OpenSSF (Linux Foundation) program.",
      "install": "Register at bestpractices.dev with GitHub, complete the checklist, embed the badge.",
      "url": "https://www.bestpractices.dev/en",
      "risk": "Low — self-assessed for Passing (Silver/Gold need evidence).",
      "verdict": "Free structured compliance audit + sales asset.",
      "pop": "OpenSSF program · recognized trust signal",
      "popRank": 3
    },
    {
      "id": "grc-platforms",
      "name": "Vanta / Drata / Secureframe",
      "aisle": "compliance",
      "type": "Web service",
      "tier": "Showroom",
      "cost": "Paid",
      "costNote": "~$5k–$25k+/yr + auditor fees",
      "what": "GRC platforms that auto-collect evidence and prep you for SOC 2 / ISO 27001 audits.",
      "why": "They do the evidence heavy-lifting — but well outside the free constraint.",
      "maturity": "Industry-leading, mature.",
      "install": "N/A — paid.",
      "url": "https://www.vanta.com/",
      "risk": "Cost is the rejection reason.",
      "verdict": "Showroom — buy ONLY when a paying customer's contract requires SOC 2. See docs/COMPLIANCE.md.",
      "pop": "Market leaders (Vanta/Drata/Secureframe)",
      "popRank": 5
    }
  ]
};
